### ISSUE TITLE
Exixe14 BOM not matching PCB

### ISSUE THREAD

**Issue by eben80** [dekuNukem/exixe#11]
Hi,
The labels on the pcb goes up to R28 while the BOM only goes to R25.
This means that i don't know the values for the bottom of pcb. 

Thank you

**Comment by dekuNukem** [comment]
Is R28 on the bottom layer? If so it is not needed. No components are soldered on bottom side.

**Comment by eben80** [comment]
Hi,
Yes the highest R value on the top layer is R24. 
So none of the 5 resistor pads need to be populated on the bottom? 
I followed the markings on the resistors of your top layer with the posted photo. 
Do you by any chance have a photo of the completed bottom of an Exixe14? 
Thank you for an awesome design.

**Comment by dekuNukem** [comment]
There are no components on the bottom layer at all, let me see if i can find a photo later today.

**Comment by eben80** [comment]
OK thank you.

**Comment by dekuNukem** [comment]
Here's a photo of the bottom side:


![](https://i.imgur.com/6Xh9Hxx.jpg)

**Comment by eben80** [comment]
Great thank you,
So just to confirm : Even though there's pads for resistors on the bottom,
they should not be populated when assembling my own.

**Comment by dekuNukem** [comment]
that is correct.

**Comment by eben80** [comment]
Thank you very much.
