### ISSUE TITLE
Overdrive doesn't seem to do anything

### ISSUE THREAD

**Issue by chrisys** [dekuNukem/exixe#12]
I'm enjoying working with my boards. I have some tubes where certain digits are slightly faded in areas, which I thought the overdrive function could help with.

I've tried enabling it (I'm using the Python library on a Raspberry Pi), but don't seem to see any difference. I don't notice any increase in brightness or any help with the faded areas, so I question if I'm using it correctly. I'm doing `exixe.Exixe(cs_pin_m, spi, overdrive=True)` when initializing. I have 3 tubes next to each other and the one with overdrive turned on looks no different to the others.

So, am I using it incorrectly, or just expecting too much? TIA for any help!

**Comment by dekuNukem** [comment]
Hi Chris:

The Python library on Raspberry Pi was ported by a contributor and I haven't tested it myself. It does seem to work on Arduino though:

![aa](https://raw.githubusercontent.com/dekuNukem/exixe/master/resources/no_overdrive.jpg)

![aa](https://raw.githubusercontent.com/dekuNukem/exixe/master/resources/with_overdrive.jpg)

It might be the library, and if you assembled and build the boards yourself, double check the components. And if you're using second-hand tubes, it might be they were so poisoned that even overdrive won't help. Although you probably should see a small difference with it being on and off. 

Best Regards,

Allen
