### ISSUE TITLE
Unable to completely turn of the LED

### ISSUE THREAD

**Issue by DunderStorm** [dekuNukem/exixe#13]
Hello!

I am unable to turn of the LED completely. When sending 

my_tube.set_led(0, 0, 0);

I still get a weak white glow from the LED.

I get the same weak white glow from the LED when I first power a fresh board without connecting it to an arduino.

Is there anyway to fix this besides desoldering R14, R15 & R16.

**Comment by dekuNukem** [comment]
This is a minor quirk that actually turned out to be slightly useful. It allows me to tell if a board is programmed or not during assembly, and it also shows if the board is powered on and working.

The dim glow won't be visible once the tube is installed, so I wouldn't worry too much about it.
