### ISSUE TITLE
Mounting methods

### ISSUE THREAD

**Issue by spgfr** [dekuNukem/exixe#14]
Is there a preferred method of mounting the exixe board to something other than a breadboard?

**Comment by chrisys** [comment]
I mounted mine with SIL headers, like this:

![Screenshot 2020-06-22 at 16 46 04](https://user-images.githubusercontent.com/521698/85307478-de47b180-b4a7-11ea-837a-84d6e80096e3.png)

Hope this helps with some ideas, at least.

**Comment by dekuNukem** [comment]
Hi Chris! Sorry for missing this issue, looks like you're using regular female headers, which is what I use myself. Looks pretty good!
